@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

### Get breadcrumbs from the database
GET https://{{host}}/api/get/about/breadcrumbs HTTP/1.1
Content-Type: {{contentType}}

### Get page details from the database
GET https://{{host}}/api/get/contact/content HTTP/1.1
Content-Type: {{contentType}}

### Get the navigation for pages
GET https://{{host}}/api/get/navigation?id=investors HTTP/1.1
Content-Type: {{contentType}}

### Post contact details
POST https://{{host}}/api/post?form=contact HTTP/1.1
Content-Type: {{contentType}}